### ISSUE TITLE
ETA? :-P

### ISSUE THREAD

**Issue by dominikzietlow** [stanfordmlgroup/disentanglement#1]
Hi guys!

Didn't expect to get an issue on an empty repository, did you? :-P
Just to be able to schedule future work (decide to evaluate it under your metric + reserving time to do so), when can we expect the code to be up?

Cheers,
Dominik

**Comment by sharonzhou** [comment]
![image](https://user-images.githubusercontent.com/2941408/105281806-cc271200-5b61-11eb-97a1-81e29b802401.png)
